# -*- coding: utf-8 -*-
"""
Created on Tue Nov 29 08:49:18 2016

@author: salo
"""
import csv

label_con = {'BehavioralDomain.Cognition.Reward': 'ParadigmClass.Reward',
             'Diagnosis.DissociativeandConversionDisorders': 'Diagnosis.ConversionDisorder',
             'Diagnosis.HighFunctioningAutism': 'Diagnosis.AutismSpectrumDisorders',
             'Diagnosis.PrimaryProgressiveAphasia': 'Diagnosis.Aphasia',
             'Diagnosis.SensoryMotorConversionDisorder': 'Diagnosis.ConversionDisorder',
             'Diagnosis.SocialAnxietyDisorder': 'Diagnosis.Anxiety',
             'Diagnosis.SpecificPhobia': 'Diagnosis.Anxiety',
             'ParadigmClass.VisualPursuitTracking': 'ParadigmClass.VisualMotion',
             'ParadigmClass.ContinuousPerformanceTask': 'ParadigmClass.GoNoGo',
             'ParadigmClass.EatingorDrinking': 'ParadigmClass.Taste',
             'ParadigmClass.Sternberg': 'ParadigmClass.DelayedMatchtoSample',
             'ParadigmClass.StopSignal': 'ParadigmClass.GoNoGo',
             'ParadigmClass.VisualDistractororVisualAttention': 'ParadigmClass.VisuospatialAttention',
             'StimType.Arrow': 'StimType.Symbols',
             'StimType.Blurreddisk': 'StimType.Shapes',
             'StimType.Dots': 'StimType.RandomDots',
             'StimType.Inhalation': 'StimType.Odor',
             'StimType.Instruction': 'StimType.Words',
             'StimType.Scenes': 'StimType.Pictures',
             'StimType.Stories': 'StimType.Words',
             'StimType.Tools': 'StimType.Pictures',
             'StimType.Traumaticscript': 'StimType.Words',
             'StimType.UniformScreen': 'StimType.None',
             'StimType.Videogame': 'StimType.VideoGame',
             'StimType.Colors': 'DROP',
             'StimType.Light': 'DROP',
             'StimType.NonverbalVocalSounds': 'DROP',
             'StimType.NonvocalSounds': 'DROP',
             'StimType.Unknown': 'DROP',
             'StimModality.Unknown': 'DROP',
             'RespType.BreatheInstructions': 'DROP',
             'RespType.Unknown': 'DROP',
             'RespModality.Unknown': 'DROP',
             'ParadigmClass.AbstractConcreteJudgement': 'DROP',
             'ParadigmClass.ActionImitation': 'DROP',
             'ParadigmClass.AttentionBias': 'DROP',
             'ParadigmClass.Classification': 'DROP',
             'ParadigmClass.DelayedMemory': 'DROP',
             'ParadigmClass.EmotionalRegulation': 'DROP',
             'ParadigmClass.FalseBelief': 'DROP',
             'ParadigmClass.FreeWordListRecall': 'DROP',
             'ParadigmClass.ImplicitAssociation': 'DROP',
             'ParadigmClass.Matching': 'DROP',
             'ParadigmClass.MemorySpan': 'DROP',
             'ParadigmClass.Mentalizing': 'DROP',
             'ParadigmClass.NonPainfulElectricalStimulation': 'DROP',
             'ParadigmClass.Posner': 'DROP',
             'ParadigmClass.Reappraisal': 'DROP',
             'ParadigmClass.SocialCognition': 'DROP',
             'ParadigmClass.SpatialorLocationDiscrimination': 'DROP',
             'ParadigmClass.SubjectiveEmotionalPictureDiscrimination': 'DROP',
             'ParadigmClass.TemporalTask': 'DROP',
             'ParadigmClass.Updating': 'DROP',
             'Instruction.Unknown': 'DROP',
             'Diagnosis.GeneticHighRiskforSchizophrenia': 'DROP',
             'Diagnosis.Historyofseriousviolence': 'DROP',
             'Diagnosis.HumanImmunodeficiencyVirus': 'DROP',
             'Diagnosis.InternetAddictionDisorder': 'DROP',
             'Diagnosis.InternetGamingAddiction': 'DROP',
             'Diagnosis.IrritableBowelSyndrome': 'DROP',
             'Diagnosis.PrenatalAlcoholExposure': 'DROP',
             'Diagnosis.PrenatalNicotineExposure': 'DROP',
             'Diagnosis.SchizophreniaandSubstanceUseDisorder': 'DROP',
             'Diagnosis.atriskstageofschizophrenia': 'DROP',
             'Diagnosis.5HTTLongVariant': 'DROP',
             'Diagnosis.5HTTShortVariant': 'DROP',
             'Diagnosis.ADRA2BDeletionCarrier': 'DROP',
             'Diagnosis.ApoE4Genotype': 'DROP',
             'Diagnosis.DTNBP1Genotype': 'DROP',
             'Diagnosis.FamilyHistoryofAlcoholism': 'DROP',
             'Diagnosis.FamilyHistoryofDepression': 'DROP',
             'Diagnosis.FamilyHistoryofSchizophrenia': 'DROP',
             'Diagnosis.MAOAGenotype': 'DROP',
             'Diagnosis.MenstruallyRelatedMoodDisorder': 'DROP',
             'Diagnosis.OrthopedicInjuries': 'DROP',
             'Diagnosis.PremenstrualDysphoricDisorder': 'DROP',
             'Diagnosis.ProbableAlzheimersDisease': 'DROP',
}

with open('/Users/salo/Desktop/label_converter.csv', 'wb') as f:
    w = csv.writer(f)
    w.writerows(label_con.items())
