#!/bin/bash 
#---Number of core
#BSUB -n 4
#BSUB -R "span[ptile=4]"

#---Job's name in LSF system
#BSUB -J ATHENAJob

#---Error file
#BSUB -eo err

#---Output file
#BSUB -oo out

#---LSF Queue name
#BSUB -q PQ_nbc

##########################################################
# Setup envrionmental variable.
##########################################################
export NPROCS=`echo $LSB_HOSTS | wc -w`
export OMP_NUM_THREADS=$NPROCS

#loads the modules (i.e., programs) you might need for your analysis
. $MODULESHOME/../global/profile.modules
module load gsl-blas/1.15
#module load python/2.7.5

source /home/data/nbc/athena/athena/bash_environment


##########################################################
##########################################################


#To call this script, in a terminal window, type:
#bsub<ModelJob.sub

#This is where you could input your example code. You can either have all your code live here, or if you have a script written, call it like you would from a terminal window.
python /scratch/jhays006/athena/test_run.py

